title: sandro zhang
description: 
email: xinshg@gmail.com

issues_repo: xinsheng/xinsheng.github.io
favicon: "logo.png"
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed